#!/bin/bash

echo "=== kLOC Measurement Report ==="
echo "Project: QLDA (Quan Ly Du An)"
echo "Generated on: $(date)"
echo "Generated by: Kilo Code Documentation Process"
echo

# Count code lines (C# files)
echo "Analyzing code files..."
CODE_FILES=$(find . -name "*.cs" -not -path "./*/bin/*" -not -path "./*/obj/*" -not -path "./*/Migrations/*" | wc -l)
CODE_LINES=$(find . -name "*.cs" -not -path "./*/bin/*" -not -path "./*/obj/*" -not -path "./*/Migrations/*" -exec cat {} \; | sed '/^\s*$/d' | wc -l)
CODE_KLOC=$(echo "scale=3; $CODE_LINES/1000" | bc 2>/dev/null || echo "0")

echo "Code Statistics:"
echo "- C# Files: $CODE_FILES"
echo "- Code Lines (non-empty): $CODE_LINES"
echo "- kLOC: $CODE_KLOC"
echo

# Count documentation lines (Markdown files)
echo "Analyzing documentation files..."
DOC_FILES=$(find ./docs -name "*.md" 2>/dev/null | wc -l)
DOC_LINES=$(find ./docs -name "*.md" 2>/dev/null -exec cat {} \; | sed '/^\s*$/d' | wc -l)
DOC_KLOC=$(echo "scale=3; $DOC_LINES/1000" | bc 2>/dev/null || echo "0")

echo "Documentation Statistics:"
echo "- Markdown Files: $DOC_FILES"
echo "- Documentation Lines (non-empty): $DOC_LINES"
echo "- kLOC: $DOC_KLOC"
echo

# Calculate ratio
if (( $(echo "$CODE_KLOC > 0" | bc -l 2>/dev/null) )); then
    RATIO=$(echo "scale=3; $DOC_KLOC/$CODE_KLOC" | bc 2>/dev/null || echo "0")
    PERCENTAGE=$(echo "scale=1; $RATIO*100" | bc 2>/dev/null || echo "0")

    echo "Documentation Ratio Analysis:"
    echo "- Ratio: $RATIO"
    echo "- Percentage: $PERCENTAGE%"
    echo

    # Assessment based on Spec Kit standards
    echo "Assessment (Spec Kit kLOC Standard):"
    if (( $(echo "$RATIO >= 0.25" | bc -l 2>/dev/null) )); then
        echo "⭐ EXCELLENT (≥25%) - Documentation exceeds requirements"
        echo "   Status: Documentation is comprehensive and detailed"
    elif (( $(echo "$RATIO >= 0.15" | bc -l 2>/dev/null) )); then
        echo "✅ GOOD (15-25%) - Documentation meets standards"
        echo "   Status: Good balance between code and documentation"
    elif (( $(echo "$RATIO >= 0.1" | bc -l 2>/dev/null) )); then
        echo "⚠️  ACCEPTABLE (10-15%) - Documentation is minimal"
        echo "   Status: Basic documentation present, consider enhancement"
    else
        echo "❌ INSUFFICIENT (<10%) - Documentation inadequate"
        echo "   Status: Immediate action required to improve documentation"
        echo "   Recommendation: Add detailed API docs, architecture diagrams, and use cases"
    fi
    echo

    # Recommendations
    echo "Recommendations:"
    if (( $(echo "$RATIO < 0.1" | bc -l 2>/dev/null) )); then
        echo "- Prioritize API documentation (Swagger + manual docs)"
        echo "- Add detailed use case descriptions"
        echo "- Create architecture diagrams"
        echo "- Document database schema and relationships"
    elif (( $(echo "$RATIO < 0.15" | bc -l 2>/dev/null) )); then
        echo "- Enhance existing documentation with examples"
        echo "- Add troubleshooting guides"
        echo "- Include performance considerations"
        echo "- Document deployment procedures"
    else
        echo "- Maintain current documentation quality"
        echo "- Focus on keeping docs synchronized with code changes"
        echo "- Consider adding video tutorials for complex features"
    fi

else
    echo "⚠️  No code files found for analysis!"
    echo "   Please ensure you're running this script from the project root."
fi

echo
echo "=== End of Report ==="
echo "For detailed documentation guidelines, see docs/update-process.md"