# kLOC Measurement Script for Windows
# Project: QLDA (Quan Ly Du An)
# Generated by: Kilo Code Documentation Process

param(
    [string]$OutputFile = "",
    [switch]$Quiet
)

function Write-Output {
    param([string]$Message)
    if (-not $Quiet) {
        Microsoft.PowerShell.Utility\Write-Host $Message
    }
    if ($OutputFile) {
        $Message | Out-File -FilePath $OutputFile -Append -Encoding UTF8
    }
}

Write-Output "=== kLOC Measurement Report ==="
Write-Output "Project: QLDA (Quan Ly Du An)"
Write-Output "Generated on: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Output "Generated by: Kilo Code Documentation Process"
Write-Output ""

# Count code lines (C# files)
Write-Output "Analyzing code files..."

$codeFiles = Get-ChildItem -Path . -Recurse -Include "*.cs" -Exclude "bin","obj","Migrations" | Where-Object { $_.FullName -notmatch "\\bin\\" -and $_.FullName -notmatch "\\obj\\" -and $_.FullName -notmatch "\\Migrations\\" }
$codeFileCount = $codeFiles.Count

$codeLines = 0
foreach ($file in $codeFiles) {
    try {
        $content = Get-Content $file.FullName -Raw
        $lines = $content -split "`n" | Where-Object { $_.Trim() -ne "" }
        $codeLines += $lines.Count
    } catch {
        Write-Output "Warning: Could not read file $($file.FullName)"
    }
}

$codeKLOC = [math]::Round($codeLines / 1000, 3)

Write-Output "Code Statistics:"
Write-Output "- C# Files: $codeFileCount"
Write-Output "- Code Lines (non-empty): $codeLines"
Write-Output "- kLOC: $codeKLOC"
Write-Output ""

# Count documentation lines (Markdown files)
Write-Output "Analyzing documentation files..."

$docsPath = Join-Path $PSScriptRoot "docs"
if (Test-Path $docsPath) {
    $docFiles = Get-ChildItem -Path $docsPath -Recurse -Include "*.md"
    $docFileCount = $docFiles.Count

    $docLines = 0
    foreach ($file in $docFiles) {
        try {
            $content = Get-Content $file.FullName -Raw
            $lines = $content -split "`n" | Where-Object { $_.Trim() -ne "" }
            $docLines += $lines.Count
        } catch {
            Write-Output "Warning: Could not read file $($file.FullName)"
        }
    }
} else {
    $docFileCount = 0
    $docLines = 0
    Write-Output "Warning: docs directory not found"
}

$docKLOC = [math]::Round($docLines / 1000, 3)

Write-Output "Documentation Statistics:"
Write-Output "- Markdown Files: $docFileCount"
Write-Output "- Documentation Lines (non-empty): $docLines"
Write-Output "- kLOC: $docKLOC"
Write-Output ""

# Calculate ratio
if ($codeKLOC -gt 0) {
    $ratio = [math]::Round($docKLOC / $codeKLOC, 3)
    $percentage = [math]::Round($ratio * 100, 1)

    Write-Output "Documentation Ratio Analysis:"
    Write-Output "- Ratio: $ratio"
    Write-Output "- Percentage: $percentage%"
    Write-Output ""

    # Assessment based on Spec Kit standards
    Write-Output "Assessment (Spec Kit kLOC Standard):"
    if ($ratio -ge 0.25) {
        Write-Output "⭐ EXCELLENT (≥25%) - Documentation exceeds requirements"
        Write-Output "   Status: Documentation is comprehensive and detailed"
    } elseif ($ratio -ge 0.15) {
        Write-Output "✅ GOOD (15-25%) - Documentation meets standards"
        Write-Output "   Status: Good balance between code and documentation"
    } elseif ($ratio -ge 0.1) {
        Write-Output "⚠️  ACCEPTABLE (10-15%) - Documentation is minimal"
        Write-Output "   Status: Basic documentation present, consider enhancement"
    } else {
        Write-Output "❌ INSUFFICIENT (<10%) - Documentation inadequate"
        Write-Output "   Status: Immediate action required to improve documentation"
        Write-Output "   Recommendation: Add detailed API docs, architecture diagrams, and use cases"
    }
    Write-Output ""

    # Recommendations
    Write-Output "Recommendations:"
    if ($ratio -lt 0.1) {
        Write-Output "- Prioritize API documentation (Swagger + manual docs)"
        Write-Output "- Add detailed use case descriptions"
        Write-Output "- Create architecture diagrams"
        Write-Output "- Document database schema and relationships"
    } elseif ($ratio -lt 0.15) {
        Write-Output "- Enhance existing documentation with examples"
        Write-Output "- Add troubleshooting guides"
        Write-Output "- Include performance considerations"
        Write-Output "- Document deployment procedures"
    } else {
        Write-Output "- Maintain current documentation quality"
        Write-Output "- Focus on keeping docs synchronized with code changes"
        Write-Output "- Consider adding video tutorials for complex features"
    }

} else {
    Write-Output "⚠️  No code files found for analysis!"
    Write-Output "   Please ensure you're running this script from the project root."
}

Write-Output ""
Write-Output "=== End of Report ==="
Write-Output "For detailed documentation guidelines, see docs/update-process.md"