namespace QLDA.Application.Common.Enums;

public enum EDanhMuc {
    [Description("Đường đi")] DmDuong,
    [Description("Phường xã")] DmPhuongXa,
    [Description("Quận huyện")] DmQuanHuyen,
    [Description("Tỉnh thành")] DmTinhThanh,
    [Description("Bước")] DanhMucBuoc,
    [Description("Bước - tình trạng dự án")] DanhMucBuocTrangThaiTienDo,
    [Description("Chủ đầu tư")] DanhMucChuDauTu,
    [Description("Hình thức đầu tư")] DanhMucHinhThucDauTu,
    [Description("Hình thức quản lý")] DanhMucHinhThucQuanLy,
    [Description("Lĩnh vực")] DanhMucLinhVuc,
    [Description("Loại dự án")] DanhMucLoaiDuAn,
    [Description("Loại dự án theo năm")] DanhMucLoaiDuAnTheoNam,
    [Description("Nguồn vốn")] DanhMucNguonVon,
    [Description("Nhóm dự án")] DanhMucNhomDuAn,
    [Description("Quy trình")] DanhMucQuyTrinh,
    [Description("Trạng thái tiến độ công việc")] DanhMucTrangThaiTienDo,
    [Description("Trạng thái dự án")] DanhMucTrangThaiDuAn,
    [Description("Màn hình")] DanhMucManHinh,
    [Description("Loại văn bản")] DanhMucLoaiVanBan,
    [Description("Chức vụ")] DanhMucChucVu,
    [Description("Loại hợp đồng")] DanhMucLoaiHopDong,
    [Description("Loại gói thầu")] DanhMucLoaiGoiThau,
    [Description("Phương thức chọn gói thầu")] DanhMucPhuongThucLuaChonNhaThau,
    [Description("Kế hoạch/Hình thức lựa chọn nhà thầu")] DanhMucHinhThucLuaChonNhaThau,
    [Description("Tình trạng khó khăn")] DanhMucTinhTrangKhoKhan,
    [Description("Tổ chức, nhà thầu")] DanhMucNhaThau,
    [Description("Danh mục giai đoạn")] DanhMucGiaiDoan,
    [Description("Danh mục mức độ khó khăn")] DanhMucMucDoKhoKhan,
    [Description("Danh mục tình trạng thực hiện LCNT")] DanhMucTinhTrangThucHienLcnt,
}