using QLDA.Domain.Entities;
using QLDA.Persistence;

namespace QLDA.Tests.Fakers;

/// <summary>
/// Seeds linked business data (DuAn → GoiThau → HopDong) for integration tests.
/// All data generated by Bogus fakers - deterministic via seed 12345.
/// </summary>
public static class BusinessDataSeeder
{
    public static async Task<BusinessDataSet> SeedAsync(AppDbContext db)
    {
        var duAn = new DuAnFaker().WithTrangThai(1).WithLoaiDuAn(1).Generate();
        db.Set<DuAn>().Add(duAn);
        await db.SaveChangesAsync();

        var goiThau = new GoiThauFaker(duAn.Id).Generate();
        db.Set<GoiThau>().Add(goiThau);
        await db.SaveChangesAsync();

        var hopDong = new HopDongFaker(duAn.Id, goiThau.Id).Generate();
        db.Set<HopDong>().Add(hopDong);
        await db.SaveChangesAsync();

        return new BusinessDataSet(duAn, goiThau, hopDong);
    }
}

/// <summary>
/// Holds seeded entities with relationships for test assertions.
/// </summary>
public record BusinessDataSet(DuAn DuAn, GoiThau GoiThau, HopDong HopDong);
