// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLDA.Persistence;

#nullable disable

namespace QLDA.Migrator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422022000_RemoveBanDauColumnsAndAddNgayQuyetDinhDuToan")]
    partial class RemoveBanDauColumnsAndAddNgayQuyetDinhDuToan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // NOTE: The full model configuration is generated by EF Core.
            // This is a simplified placeholder to indicate the migration structure.
            // The actual model configuration will be merged with the snapshot.
#pragma warning restore 612, 618
        }
    }
}
